[project]
name = "fair-synthesis"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pyzmq>=27.1.0",
]

readme = "README.md"

authors = [
    { name = "Felix Neubauer" },
    { name = "Kenichi Endo" },
    { name = "Frederic Bender" }
]

[tool.uv]
package = true